Add sorting features
wihary/HEROES pull request #13
Opened 2019-01-21 21:40 UTC by avondero

- Add sorting features on server side
- Extract business logic from some views

2019-01-21 21:40 UTC, avondero commented
Fixes #13

2019-01-22 07:16 UTC, wihary requested changes
Globalement j'aime bien la solution, peut être ajouter une petite icone en mode fleche a cote du nom de la colonne en appliquant un tri par défaut. Au pire ca peut être vue après la PR

Commentaires généraux:

- [x] fichier ComicsBrowserComponent.cshtml.cs ne respecte pas le nommage et ne correspond pas au nom de la classe qu'il porte

- [ ] Attention aux commentaires il faudrait que l'on fasse une passe pour améliorer la doc du code

- [x] Modifier les string.format et les retours a la ligne intempestifs ^^

- [x] Ajouter les commentaires dans IQueryableExtensions

2019-03-08 20:23 UTC, wihary submitted a review, later dismissed

2019-03-08 20:35 UTC, wihary commented
is it building this time ? :D

2019-03-08 21:03 UTC, wihary approved these changes

2019-03-08 21:04 UTC, merged